# SpringBoot
spring.web.resources.add-mappings=true

# SolidSign API Auth & Endpoint Configuration
solidsign.api.url=https://solidsign.com.br/solidsign/dsig/pdf/sign-pkcs12
solidsign.api.token=Bearer YOUR_JWT_TOKEN_HERE

# Certificate and File Paths / Caminhos de arquivo e certificado / Rutas de arquivos y certificados
# **PFX/P12 certificate** repository file (.pfx, .p12). 
# Note: By sending this file to the SolidSign API SaaS environment (if applicable), you authorize the temporary processing 
# of the certificate for signing purposes in accordance with the SolidSign API terms of service. 
# This information will only remain in the server while the signature process is underway. You can access the full Terms of Service in
# `https://solidsign.com.br/solidsign/termsofservice`
solidsign.cert.path=C:/Users/User/Desktop/UserFileCertificate.pfx
solidsign.cert.password-base64=MTIz...

# Signature Appearance
# List of image paths separated by commas
# If multiple images are sent, they must be equal to the number of documents to be signed
solidsign.sig.image-paths=C:/Users/User/Desktop/stamp_signature.png, C:/Users/User/Desktop/company_logo.png
# Settings for the signature box (coordinates of placement, page of placement, width/height of signature field, etc.)
solidsign.sig.field-config=[{ "coordinateX": 30, "coordinateY": 30, "page": "FIRST_PAGE", "width": 60, "height": 150 }]

# Signature Settings
solidsign.sig.hash-algorithm=SHA256

# Profile/SignatureLevel for the produced signatures:
# International PDF Standard: PDF_BASIC, PDF_TIMESTAMP, PDF_COMPLETE
# PBAD/ICP-Brasil Standard: ADRB, ADRT, ADRC, ADRA
# ETSI Baseline Standard: PADES_B, PADES_T, PADES_LT, PADES_LTA.
solidsign.sig.profile=ADRT

# Measurement unit for the width and height of Signature Field: MILLIMETERS (Official adobe measurement), PIXELS
solidsign.sig.unit=PIXELS

# i18n Locale for the current instance of SolidSign-API (Available Languages: en_US, pt_BR, es_ES)
# This will define the language of Swagger Docs and Error messages
app.locale=en_US

# Defines which port will be used by the SolidSign-API Example Application    
server.port=8080

# Swagger UI Config (Don't modify any value here, only `app.locale` on top of file)
spring.messages.basename=bundle/messages
spring.messages.encoding=UTF-8
spring.web.locale=${app.locale}
spring.web.locale-resolver=fixed
springdoc.api-docs.resolve-external-entities=true
springdoc.cache.disabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.hateoas.enabled=false
spring.mvc.encoding.charset=UTF-8
spring.mvc.encoding.enabled=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
springdoc.writer-with-default-pretty-printer=true

# Tomcat config
tomcat.ajp.enabled=false
tomcat.ajp.port=8021

app.name=SolidSign-Example-PDF-PKCS12
app.version=1.0.0